// import React from 'react'

export default function Ex6() {
    return (
        <div className="w-[200px] h-[200px] overflow-auto">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed omnis deleniti eaque vero aperiam dicta consectetur autem vitae magnam consequuntur facere, molestias temporibus nulla vel, eveniet nihil dolorum optio rerum.
            Incidunt alias tempora facilis, at minus esse velit cupiditate sint dignissimos animi. Quibusdam est, quas atque reiciendis sed, recusandae, molestias ipsum dolorum doloremque nesciunt libero ut! Eligendi, tempora? Asperiores, rem.
            Culpa doloremque necessitatibus ab veritatis, labore veniam minus perspiciatis? Adipisci eos quae consequatur. Dolorum asperiores quis natus sunt, cum, ducimus perferendis expedita dolorem, veritatis nobis ad molestiae id dignissimos obcaecati.
            Similique ea ex assumenda numquam laboriosam perspiciatis nesciunt illo omnis cupiditate ut et soluta nostrum, veniam dolore iusto architecto repellat! Nobis earum dolores recusandae inventore commodi nostrum maiores impedit excepturi!
            Omnis officia sapiente quis excepturi deserunt! Dolor harum inventore iusto amet obcaecati quod voluptates? Accusantium facere unde nemo commodi. Sit eveniet libero ratione, eaque cumque vitae aperiam odit ad suscipit.
            Nobis corrupti accusantium illo quam? Excepturi fuga veritatis ipsum voluptatum numquam quas. Saepe quia non ipsam sed laborum, esse harum iste voluptate. Quaerat, esse vitae. Ullam deleniti nulla similique dolore.
            Quam cum error ipsam earum doloribus vel, natus esse mollitia quidem impedit quos praesentium voluptatibus autem architecto dolores enim vero sint sapiente fugit. Ullam, necessitatibus doloribus perspiciatis magni atque neque.
            Tempore aspernatur explicabo esse velit obcaecati vero fuga nobis asperiores laboriosam. Ullam alias eveniet quidem commodi, enim iste earum explicabo vero molestias, asperiores molestiae adipisci ipsum mollitia? Quam, perferendis maxime?
            Doloremque illum ab minus magnam nihil odit quibusdam quia labore, explicabo quis expedita, nisi hic inventore ipsa accusamus perspiciatis voluptatum dolorum dolorem ea necessitatibus commodi unde eos. Consequuntur, minima accusamus!
            Maxime asperiores inventore optio velit voluptatem quisquam illum laborum dignissimos sequi repellat necessitatibus a porro, assumenda nostrum explicabo nulla ratione? Non eum numquam deserunt alias eveniet unde quae beatae iure?
            Laudantium, necessitatibus! Repellat quod praesentium maiores et id, quas delectus quos sunt incidunt excepturi hic odit autem, dignissimos eaque eveniet eos expedita! Numquam pariatur cum nobis, in neque beatae sunt.
            Pariatur modi, eligendi temporibus doloribus perspiciatis ducimus explicabo excepturi nemo, totam consectetur nostrum facilis! Atque sequi iusto maxime itaque adipisci dolor. Nesciunt delectus explicabo maxime beatae molestiae quos. Iusto, veniam?
            Veniam enim natus ea cupiditate asperiores repellendus odit perferendis vitae iure, veritatis tempore temporibus. Ipsum veritatis facilis perferendis explicabo aliquam. Neque autem voluptatem eaque adipisci aliquam ex magni fugit. Ea?
            Explicabo aut accusantium error iure, at quasi hic saepe quo porro culpa quam architecto deserunt rem, cumque repellat similique officia, ut molestiae cum aspernatur perspiciatis ad soluta sapiente sint! Est?
            Aliquid voluptatum voluptas ipsa et eius esse pariatur, numquam, tempora eveniet a rerum commodi temporibus impedit. Eveniet illum labore eaque, dolor officia facilis cupiditate dicta est in totam quod obcaecati!
            Architecto fuga commodi nihil velit ipsa. Necessitatibus, dolor quo, omnis sunt magni, reprehenderit iure iste sed provident vitae tempore! Nesciunt adipisci quam quasi veniam magnam id odio praesentium ullam consequatur!
            Ullam corrupti quia reprehenderit aperiam eveniet ad perferendis facilis at fuga molestias tenetur, ipsum repellendus, consectetur odio molestiae quaerat aliquid id? Autem iste explicabo magni numquam provident quos corrupti debitis.
            Quaerat natus doloribus nesciunt? Animi, consequatur. Rem harum magnam consectetur illo. Non cum mollitia ipsum incidunt fugiat maxime, quaerat officia dolorum doloribus atque harum voluptate quo, voluptas accusamus neque odit.
            In iusto animi officiis fugit qui, corrupti quibusdam! Vero, asperiores. Consequuntur illo dolor doloremque, eos quis nobis, libero soluta eum culpa numquam esse odio eius perferendis asperiores. Quaerat, sint perferendis.
            Sit harum, vero aut porro consequuntur corrupti pariatur eius sed! Libero totam eos, consequuntur minima maiores deleniti odio doloremque est optio error, quia nesciunt. Alias eius architecto odit? Excepturi, harum?
            Incidunt, distinctio maiores officia aliquam mollitia earum nam aperiam perferendis deleniti odit? Quas saepe nam quos quae. Magnam itaque omnis atque! Ad dolores iusto, a beatae qui excepturi ipsa harum.
            Praesentium expedita vitae nam dolorem facilis voluptatum ex odio doloremque suscipit, labore similique a iure. Quisquam provident veniam harum eligendi voluptates veritatis quibusdam quasi id nulla consequuntur, quaerat inventore quidem!
            Reprehenderit iste voluptatem quia! Dolore porro tempore incidunt beatae fugit nostrum voluptatem nemo sapiente tenetur, a, cum molestiae labore facere reprehenderit facilis neque, corrupti amet veritatis in eaque placeat exercitationem?
            Nostrum corporis explicabo at modi voluptas officia praesentium doloremque perspiciatis sint facere voluptate animi autem veniam incidunt velit totam mollitia deleniti repudiandae, atque possimus itaque! Dolorem aperiam sapiente voluptatum quisquam.
            Itaque sed corporis obcaecati. Quia delectus sint assumenda placeat omnis molestias eum odio corporis, magni obcaecati? Nulla ex sit necessitatibus maiores deserunt vero officiis magni, autem dicta qui omnis veniam.
            Harum est nemo recusandae, qui soluta mollitia quia similique perspiciatis labore quam aliquam fugiat, eligendi magnam? Recusandae tenetur ab ipsam dignissimos, nam commodi est illum deleniti, autem debitis sunt voluptas!
            Enim nostrum facilis eveniet. Quod in provident, culpa corrupti voluptatibus quis, consectetur eligendi voluptatem commodi blanditiis nam a nobis inventore ab modi laborum dolorem praesentium itaque laboriosam! Deleniti, incidunt nobis?
            Beatae porro, ut, nisi mollitia nihil molestias officia vero, excepturi voluptate nam autem minima non neque minus itaque quibusdam earum consequatur qui quae est. Dolorum magni quaerat sint molestias neque?
            Nobis dolores adipisci facilis vel dicta ipsa mollitia commodi? Nostrum praesentium non perspiciatis iure, quo sunt? Consequatur officiis iure maiores eum excepturi optio sed tempore quas aut, molestias delectus sunt!
            Vitae nulla magnam quod nesciunt harum mollitia autem nemo aliquid, laborum delectus rerum consequatur error officiis nostrum magni, et est explicabo repellendus. Eaque reiciendis laborum, tempora dolorum quod a laudantium.
            Nulla consequuntur rerum ducimus labore dolor fugiat molestias ex ad soluta doloribus tenetur provident tempore, harum, debitis deserunt. Nam reiciendis quaerat maiores earum beatae quidem dolorem obcaecati. Rem, excepturi sit!
            Doloremque exercitationem unde quidem possimus tenetur ratione expedita perspiciatis dignissimos incidunt autem? Laborum quia architecto nihil delectus aut ad magni similique eum repellendus labore? Qui eaque praesentium voluptas molestias distinctio.
            Ducimus fuga officiis adipisci sunt aut nemo excepturi voluptates ad consequuntur sapiente. Iste aspernatur officiis, numquam distinctio earum similique debitis quisquam, itaque neque qui fugit deleniti iusto ea totam et!
            Obcaecati optio non nesciunt perferendis voluptatum voluptate voluptatibus facilis sit cum, atque ipsum beatae ut nisi. Ut officiis assumenda totam? Beatae labore placeat ipsum asperiores quae eius assumenda tempore perspiciatis?
            Magnam, non, sit, modi in aut autem nam tempore ab qui impedit ipsa quo reiciendis vel porro! Impedit odit voluptatum iusto sint repellendus placeat cupiditate explicabo, numquam fuga facere suscipit!
            Commodi, vero! Delectus dolor, et iure magnam maiores fugit? In nulla maxime accusantium beatae ipsam quam libero facilis eum quo ipsum ipsa nihil, aliquam consectetur eos. Fugiat sunt asperiores delectus.
            Aperiam veniam nobis id, cumque ullam rem excepturi tenetur alias maiores quaerat quis perspiciatis totam unde odio? Distinctio cupiditate officiis optio, exercitationem aperiam perspiciatis ipsum. Corporis praesentium eum fugiat omnis.
            Voluptates nostrum quae debitis unde vitae facilis ea repellendus est saepe aliquid, nesciunt tenetur itaque exercitationem voluptas sed culpa eos quas eum quaerat corporis nihil necessitatibus consequuntur illum soluta. Neque!
            Aliquid aliquam totam numquam mollitia fuga, repellendus, doloremque cupiditate illum voluptas corporis adipisci quisquam recusandae non aut facere libero exercitationem sed possimus? Laborum delectus odio quasi labore, obcaecati laboriosam harum!
            Asperiores odit, deserunt voluptatum ratione nobis ducimus quo quidem eaque nulla aut tempore et ipsam illo natus molestias qui optio voluptatibus, maxime harum accusantium cum! Culpa nemo ipsa porro omnis?
            Porro veritatis, id vero expedita deleniti numquam dignissimos eveniet, nisi dolorum aspernatur fugit animi. Nulla maiores possimus voluptatibus itaque cum quia eveniet voluptatem doloribus, nostrum eos dicta ipsum, debitis fugit?
            Ex ab consectetur nisi nostrum, quisquam minus? Fugit laudantium eveniet dolorem nesciunt at. Vitae, neque. Recusandae dolorem explicabo veritatis, quis asperiores hic rem, eligendi ab vitae, esse omnis. Odit, dolorum.
            Vel molestias rem ipsa officia reprehenderit quas atque quaerat consequatur eligendi nemo voluptatem, pariatur omnis quibusdam odit. Quisquam, cupiditate? Quae aliquam voluptatem architecto aut facere illum tempora, odit amet qui?
            Neque nulla distinctio dolorum dolor. Fugit atque harum porro aut voluptatibus ut vel a sunt eum! Soluta, ad impedit delectus, ipsa fugiat culpa illum quia, sunt voluptatibus consequuntur nobis eligendi!
            Et eius, eum consectetur at cum incidunt optio! Harum, voluptas, dolor vitae eius et debitis ipsam natus nulla aliquam dignissimos nihil expedita reprehenderit omnis veniam odio blanditiis quos a totam.
            Mollitia dolor nulla ex aspernatur repellendus velit laudantium veritatis, quas ad voluptatem id, libero odio, quam atque quidem ut possimus deleniti quaerat. Exercitationem aspernatur voluptate officia expedita, sunt ex consequuntur!
            Commodi magnam quis accusamus reprehenderit asperiores exercitationem, sapiente vitae animi excepturi, saepe nulla laudantium ad dignissimos nisi modi, quas delectus. Velit harum cumque vel doloremque id accusamus iusto quaerat. Harum.
            Laudantium dolore placeat illo a, optio quas assumenda ducimus harum esse error adipisci consectetur vitae velit fugit non animi veniam aspernatur laborum molestias repudiandae officiis quod autem neque! Eum, aliquid?
            Possimus, hic ullam ad, consequuntur deserunt impedit at officia voluptatum voluptas quis dolore eligendi cupiditate error doloribus voluptatibus amet, sunt officiis sit perferendis! Sint perferendis error voluptas aspernatur maxime omnis.
            Porro soluta a cum consectetur quidem, aperiam amet ipsa qui excepturi officia minima, maiores quisquam et rerum eligendi dolore earum at repudiandae eius. Sint dolore, nihil similique corporis tempora fuga.</p>
        </div>
    )
}
